name: Plugin integration test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        wp-version:
          - "5.0"
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "5.7"
        exclude:
          # Containers not available
          - php-version: "8.0"
            wp-version: "5.0"
          - php-version: "8.0"
            wp-version: "5.1"
          - php-version: "8.0"
            wp-version: "5.2"
          - php-version: "8.0"
            wp-version: "5.3"
          - php-version: "8.0"
            wp-version: "5.4"
          - php-version: "8.0"
            wp-version: "5.5"
          - php-version: "7.4"
            wp-version: "5.0"
          - php-version: "7.4"
            wp-version: "5.1"
          - php-version: "7.4"
            wp-version: "5.2"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create .env file
        run: cp env.example .env
      - name: Start the stack
        run: docker-compose up -d
        env:
          WP_VERSION: ${{ matrix.wp-version }}
          PHP_VERSION: ${{ matrix.php-version }}
      - name: Wait for containers to start
        run: sleep 30
      - name: install test requirements
        run: pip install -r tests/requirements.txt
      - name: run tests
        run: pytest
        working-directory: ./tests
